# Generated by Django 4.1.3 on 2022-12-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFilterModification',
            new_name='ProductItemModification',
        ),
    ]
