# Generated by Django 4.1.3 on 2022-12-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtermodification',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
            preserve_default=False,
        ),
    ]
