# Generated by Django 4.1.3 on 2022-12-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_filtermodification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
    ]
