# Generated by Django 4.1.3 on 2022-12-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='api.product'),
        ),
    ]
