# Generated by Django 4.1.3 on 2022-12-08 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_productitemmodification_product_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificationvalue',
            name='filter_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_value', to='api.filtermodification'),
        ),
    ]
