# Generated by Django 4.1.3 on 2022-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_modificationvalue_filter_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtermodification',
            name='is_displayable',
            field=models.BooleanField(default=False),
        ),
    ]
