# Generated by Django 4.1.3 on 2022-12-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_filtermodification_is_displayable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='filtermodification',
            name='is_displayable',
        ),
        migrations.AddField(
            model_name='filtermodification',
            name='display_option',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.displayoption'),
        ),
    ]
