# Generated by Django 4.1.3 on 2022-12-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_displayoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
    ]
