# Generated by Django 4.1.3 on 2022-12-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='item_img',
            field=models.FileField(upload_to='', verbose_name='item_image'),
        ),
    ]
